### Get all users
GET http://127.0.0.1:3000/api/v1/users

### Get user 3609 data
GET http://127.0.0.1:3000/api/v1/users/690def7093d8affbddd8cca5

### Get user with malformed id
### Expecting malformed input error message
GET http://127.0.0.1:3000/api/v1/users/690def7093d8affbddd8c332

### Get user with non-existing id
# expecting error 404
GET http://127.0.0.1:3000/api/v1/users/10000


### PUT user 3609 data
PUT http://127.0.0.1:3000/api/v1/users/3609
Content-Type: application/json

{
  "username": "bingo"
}

### DELETE user 3609 data
DELETE http://127.0.0.1:3000/api/v1/users/3609



### Add user named Frank
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
    "name": "john",
    "username": "johndoe",
    "email": "john@metropolia.fi",
    "role": "admin",
    "password": "password"
}



### Add user named Matti
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
    "name": "Matti",
    "username": "MattiUser",
    "email": "matti2@metropolia.fi",
    "role": "admin",
    "password": "password"
}


### Add user with missing name
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
    "username": "johndoe",
    "email": "john@metropolia.fi",
    "role": "user",
    "password": "password"
}


### Post login
POST http://127.0.0.1:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password"
}
